#[]

- alias: 'Woonkamerlamp aan bij avond'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      entity_id: light.Woonkamer_plafond
      data:
        brightness: 50
    - service: light.turn_on
      entity_id: light.Woonkamer_hoek
    - service: light.turn_on
      entity_id: light.surface_achter
    - service: light.turn_on
      entity_id: light.woonkamer_balk

- alias: 'Woonkamerlamp toggle met muurschakelaar'
  trigger: 
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_158d000183ceff 
      click_type: single
  action:
    service: light.toggle
    entity_id: light.Woonkamer_plafond

- alias: 'TV-lamp toggle met cube flip'
  trigger:
    platform: event 
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001031fb8
      action_type: flip90
  action: 
    service: light.toggle
    entity_id: light.gateway_light_286c07f09ac5

- alias: 'Alle lampen uit bij dubbelklik'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016c0722
      click_type: double
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_286c07f09ac5
    - service: light.turn_off
      entity_id: light.Woonkamer_plafond
    - service: light.turn_off
      entity_id: light.Slaapkamer_plafond
    - service: light.turn_off
      entity_id: light.Slaapkamer_balk

- alias: 'Slaapkamerlamp aan met knop'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016c0722
      click_type: single
  action:
   - service: light.toggle
     entity_id: light.Slaapkamer_plafond

- alias: 'Slaapkamerlamp full brightness met hold'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016c0722
      click_type: hold
  action:
    service: light.on
    entity_id: light.Slaapkamer_plafond
    data:
      brightness: 100
  # - service: notify.publicservice
  #   data: 
  #    message: "Slaapkamerlamp getrekkerd met de knop in slaapkamer"

- alias: 'Slaapkamerlamp aan om 21:30'
  trigger:
    platform: time
    at: '21:30:00'
  action:
    service: light.turn_on
    entity_id: light.Slaapkamer_plafond
    data:
      brightness: 50

- alias: 'Slaapkamerlamp aan om 6:00'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.Slaapkamer_plafond
    data:
      brightness: 30

- alias: 'PC via Xiaomi Cube - Shake'
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
       entity_id: binary_sensor.cube_158d0001031fb8
       action_type: shake_air
  action:
    service: switch.turn_on
    entity_id: switch.gaming_pc
