homeassistant:
  name: FlanLAN
  latitude: 52.78016
  longitude: 6.23431
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include names.yaml

frontend:
config:
http:
   base_url: home.fland.re
   api_password: !secret http_api
   ip_ban_enabled: True
   login_attempts_threshold: 3
updater:
  include_used_components: true
media_player: !include cast.yaml
conversation:
history:
logbook:
sun:
notify: !include notify.yaml
device_tracker: !include device_tracker.yaml
light: !include lights.yaml
xiaomi_aqara: !include xiaomi.yaml
group: !include groups.yaml
automation: !include automations.yaml
weather: !include weather.yaml
sensor: !include sensor.yaml
#vacuum: !include vacuum.yaml
tts:
 - platform: google
   cache: true
   cache_dir: /tmp/tts
   language: 'nl'
switch: !include switches.yaml
